on: 
  push:
    tags:
      '*'
jobs:
  build-project:
    runs-on: windows-2022
    defaults:
      run:
        shell: cmd
    strategy:
      matrix:
        presets:
        - architecture: x64
          output_prefix: x64\
        - architecture: x86
          output_prefix: 
    steps:
      - name: update-vs-step1
        run: echo "Hello World" && "C:\Program Files (x86)\Microsoft Visual Studio\Installer\setup.exe" modify --add "Microsoft.VisualStudio.Component.VC.Tools.x86.x64" --installPath "C:\Program Files\Microsoft Visual Studio\2022\Enterprise" --quiet
      - name: update-vs-step2
        run: echo "Hello World" && "C:\Program Files (x86)\Microsoft Visual Studio\Installer\setup.exe" modify --add "Microsoft.VisualStudio.Component.VC.Runtimes.x86.x64.Spectre" --installPath "C:\Program Files\Microsoft Visual Studio\2022\Enterprise" --quiet
      - uses: actions/checkout@v2
        with: 
          path: project
          submodules: 'true'
      - run: git pull
        working-directory: C:\vcpkg
      - run: vcpkg upgrade --no-dry-run
        working-directory: C:\vcpkg
      - run: vcpkg integrate install
        working-directory: C:\vcpkg
      - name: install-requirements
        run: C:\vcpkg\vcpkg.exe install --triplet=${{ matrix.presets.architecture }}-windows-static @.vcpkg_deps.txt
        working-directory: .\project
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.presets.architecture }}
          spectre: true
      - name: build-project
        run: msbuild ./hide-window-from-capture.sln /p:Configuration=Release /p:Platform=${{ matrix.presets.architecture }} /p:PlatformToolset=v143 /p:WindowsTargetPlatformVersion=10.0.22621.0
        working-directory: .\project
      - name: clean-build-temp
        run: del "*.pdb"
        working-directory: .\project\${{ matrix.presets.output_prefix }}Release
      - name: rename-build-folder
        run: ren Release hide-window-from-capture
        working-directory: .\project\${{ matrix.presets.output_prefix }}
      - run: dir ${{github.workspace}}\project\${{ matrix.presets.output_prefix }}
      - run: dir ${{github.workspace}}\project\${{ matrix.presets.output_prefix }}hide-window-from-capture
      - uses: actions/upload-artifact@v2
        with: 
          name: project${{ matrix.presets.architecture }}
          path: ${{github.workspace}}\project\${{ matrix.presets.output_prefix }}hide-window-from-capture
          retention-days: 1
  make-release:
    runs-on: windows-2022
    needs: build-project
    defaults:
      run:
        shell: cmd
    steps:
      - uses: actions/download-artifact@v2
        with: 
          name: projectx86
          path: C:\hide-window-from-capture-x86
      - uses: actions/download-artifact@v2
        with: 
          name: projectx64
          path: C:\hide-window-from-capture-x64
      - name: make-release-archive-x64
        run: 7z a C:\hide-window-from-capture-x64.zip C:\hide-window-from-capture-x64
        working-directory: C:\
      - name: make-release-archive-x86
        run: 7z a C:\hide-window-from-capture-x86.zip C:\hide-window-from-capture-x86
        working-directory: C:\
      - name: do-release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            C:\hide-window-from-capture-x64.zip
            C:\hide-window-from-capture-x86.zip
      